create table if not exists public.store_reviews (
  id bigint generated by default as identity primary key,
  store_id text not null,
  user_id uuid not null,
  drink real not null check (drink >= 1 and drink <= 5),
  hygiene real not null check (hygiene >= 1 and hygiene <= 5),
  atmosphere real not null check (atmosphere >= 1 and atmosphere <= 5),
  final_score real not null check (final_score >= 1 and final_score <= 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (store_id, user_id)
);

-- 기존 테이블이 있다면 comment 컬럼 추가
alter table public.store_reviews add column if not exists comment text;

alter table public.store_reviews enable row level security;

drop policy if exists "store_reviews_select_all" on public.store_reviews;
create policy "store_reviews_select_all"
  on public.store_reviews
  for select
  to anon, authenticated
  using (true);

drop policy if exists "store_reviews_insert_own" on public.store_reviews;
create policy "store_reviews_insert_own"
  on public.store_reviews
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop function if exists public.submit_store_rating(text, numeric, numeric, numeric, numeric);
drop function if exists public.submit_store_rating(text, numeric, numeric, numeric, numeric, text);

create or replace function public.submit_store_rating(
  p_store_id text,
  p_drink numeric,
  p_hygiene numeric,
  p_atmosphere numeric,
  p_final numeric,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_reviews jsonb;
begin
  if v_user_id is null then
    raise exception 'loginRequired';
  end if;

  if not exists (
    select 1
      from public.stores
      where id::text = p_store_id
  ) then
    raise exception 'storeNotFound';
  end if;

  insert into public.store_reviews (
    store_id,
    user_id,
    drink,
    hygiene,
    atmosphere,
    final_score,
    comment
  )
  values (
    p_store_id,
    v_user_id,
    p_drink::real,
    p_hygiene::real,
    p_atmosphere::real,
    p_final::real,
    p_comment
  );

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'user_id', user_id::text,
        'drink', drink,
        'hygiene', hygiene,
        'atmosphere', atmosphere,
        'final', final_score,
        'comment', comment,
        'created_at', created_at
      )
      order by created_at desc
    ),
    '[]'::jsonb
  )
    into v_reviews
    from public.store_reviews
    where store_id = p_store_id;

  return v_reviews;
exception
  when unique_violation then
    raise exception 'alreadyRated';
end;
$$;

revoke all on function public.submit_store_rating(text, numeric, numeric, numeric, numeric, text) from public;
grant execute on function public.submit_store_rating(text, numeric, numeric, numeric, numeric, text) to authenticated;
