// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpS2NCu-uCzEPf3LOqHWMLVWDAks8UxJk',
    appId: '1:1018243169551:web:30d7c2f6f255830df7127a',
    messagingSenderId: '1018243169551',
    projectId: 'placelist-5bacb',
    authDomain: 'placelist-5bacb.firebaseapp.com',
    storageBucket: 'placelist-5bacb.firebasestorage.app',
    measurementId: 'G-YR04VKLPNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tvmwvnyx_lH9Mf3UEVakxDFK2nHj9-o',
    appId: '1:1018243169551:android:7abc48a3c34e2ee6f7127a',
    messagingSenderId: '1018243169551',
    projectId: 'placelist-5bacb',
    storageBucket: 'placelist-5bacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdcgtukacGaptX3gbzpDjqOudNUkZso8',
    appId: '1:1018243169551:ios:9cc799db4d91acddf7127a',
    messagingSenderId: '1018243169551',
    projectId: 'placelist-5bacb',
    storageBucket: 'placelist-5bacb.firebasestorage.app',
    iosBundleId: 'com.wawau.placelist',
  );

}