name: iOS Test Build

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Flutter가 타겟을 13.0으로 복구하지 못하도록 빌드 전 환경 설정을 15.0으로 강제 고정합니다.
      - name: Force iOS 15.0 Deployment Target
        run: |
          flutter config --ios-signing-development-team=3G639295RM
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS (No Sign)
        run: flutter build ios --no-codesign --release

      - name: Build IPA
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: Runner.ipa